### ISSUE TITLE
CMake imported target

### ISSUE THREAD

**Issue by vmartinlac** [Framstag/libosmscout#1276]
Hello,

If I try to link against libosmscout, I get

```
-- Configuring done
-- Generating done
-- Build files have been written to: /home/victor/depotoir/aa
ninja: error: 'OSMScout::OSMScout-NOTFOUND', needed by 'some_executable', missing and no known rule to make it
```

My dummy CMakeLists.txt is 

```
cmake_minimum_required(VERSION 3.0)
project(some_project)
find_package(libosmscout REQUIRED)
add_executable(some_executable main.cpp)
target_link_libraries(some_executable PUBLIC  OSMScout::OSMScout)
```

The problem disappears if I add the following line to libosmscoutConfig.cmake:

```
set_property(TARGET OSMScout::OSMScout APPEND PROPERTY IMPORTED_LOCATION  ${LIBOSMSCOUT_OSMScout_LIB_RELEASE})
```
So it seems that the error was coming from the property IMPORTED_LOCATION not being filled.

My configuration is:
- Ubuntu 20.04
- ninja build system

**Comment by Framstag** [comment]
@vmartinlac I have not written some defauls of the cmake support, so some questions:
 I assume that you have build and installed libosmscout before? To which location? Which applications, libraries did get build - ans which not?

find_package should resolve to a postprocessed version of cmake/libosmscoutConfig.cmake.in.  

Can you attach the resulting *.cmake file?

@Karry: Can you help? It would take me some time to get into these scripting parts of cmake. Perhaps we should have a Dockerfile for such test scenario at hand?

**Comment by vmartinlac** [comment]
Here is a Dockerfile to reproduce the bug.

Dockerfile
```
FROM ubuntu:20.04

COPY setup.sh /root/setup.sh
COPY CMakeLists.txt /root/test/
COPY main.cpp /root/test/

RUN bash /root/setup.sh
```

setup.sh
```
set -e
export TZ=Europe/Paris
ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
apt update
apt upgrade --yes
apt install --yes git build-essential cmake libcairo2-dev
cd /root/
git clone https://github.com/Framstag/libosmscout.git
cd libosmscout
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Release
make -j8 install
cd /root/test/
cmake . -Dlibosmscout_DIR=/root/libosmscout/install/lib/cmake/libosmscout/
make
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.1)
project(test)
find_package(libosmscout REQUIRED)
add_executable(test main.cpp)
target_link_libraries(test PUBLIC OSMScout::OSMScout)
```

main.cpp
```
int main(int num_args, char** args)
{
    return 0;
}
```

Only the last line of setup.sh fails :
```
CMakeFiles/test.dir/build.make:82: *** target pattern contains no '%'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:75: CMakeFiles/test.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
The command '/bin/sh -c bash /root/setup.sh' returned a non-zero code: 2
```

**Comment by Karry** [comment]
Hi. I am not cmake expert, for me it is always pain :-) I prepared merge request that should fix it: https://github.com/Framstag/libosmscout/pull/1279

I tested it with simple demo app: https://github.com/Karry/osmscout-cmake-demo

**Comment by vmartinlac** [comment]
Hello, the issue remains. From my understanding, with Make and Ninja (which are mono-configuration and are the only build systems available on linux), cmake does not read IMPORTED_LOCATION_<CONFIG> properties. It only reads IMPORTED_LOCATION.

**Comment by vmartinlac** [comment]
Hello, I confirm that it compiles if CMAKE_BUILD_TYPE is set correspondingly in the user project. However, in libosmscout cmake import file, debug and release variants are marked as found even when they are not available. This config file can be produced automatically by cmake using the command "export(TARGETS ...)".

**Comment by Framstag** [comment]
@vmartinlac Do you have a concrete code change proposal? Something that further enhances @Karry fix?
