### ISSUE TITLE
Segfault when routing

### ISSUE THREAD

**Issue by rinigus** [Framstag/libosmscout#148]
Reported originally by @otsaloma [ https://github.com/rinigus/osmscout-server/issues/31 ]

When calculating a route in Helsinki, using Mapzen Metro extract https://mapzen.com/data/metro-extracts/metro/helsinki_finland/ , routing leads to segfault. To reproduce:

./Demos/Routing --car ../../map/helsinki_finland 60.1674 24.9426 60.193096 24.900393

Using the current version (changed few hours ago), the code crashes at 

https://github.com/Framstag/libosmscout/blob/bf2242832c27cd82e3161b5c3507ed6cdcb0e0c2/libosmscout/src/osmscout/RoutingService.cpp#L304

Maybe it has to be compared to the closedSet.end() as well? I tried to add that in the previous version and, as I could tell, it did help against the segfault on that position, but the routing crashed a bit later then.

**Comment by Framstag** [comment]
I can reproduce the problem locally. I assume that problem was already there before my last change (CloseMap => ClosedSet)? This information would help me during analysis. I try to look at this as soon as possible.

**Comment by rinigus** [comment]
Tim, yes the bug was there before. I am very sorry that I couldn't fix it myself. I did play with it a bit, but, in the end, it seemed reasonable to submit as an issue over here.

**Comment by Framstag** [comment]
No problem. With a nice reproducer the cause was easy to find. I pushed a fix - though I did not validate the resulting route. 

I also added some asserts to get a clear error if such thing occurs again.

**Comment by rinigus** [comment]
I will check whether it works on ARM as well. On desktop, it fixed an issue. On ARM, let me recheck by recompiling everything. Just recompile of the lib did not help and I was still getting segfaults. I'll report back here when I manage to test a bit more

**Comment by rinigus** [comment]
On phone, I am still getting segfaults. Don't know why its different for phone and desktop, but here is the debugger output (pasted from terminal, sorry)

Automatically closing FileScanner for fi
le '/home/nemo/Maps/helsinki_finland/loc
ation.idx'!
60.1674 24.9426
60.1931 24.9004
From:                Way 819602[1 *> 379
5564248010254337]
To:                  Way 1903176[3795564
573467080705 >* 1 *> 3795564590575395841
]
Time:                0.121
Route nodes loaded:  6695
Route nodes ignored: 12495
Max. OpenList size:  174
Max. ClosedSet size: 6621
[New LWP 20365]

Program received signal SIGSEGV, Segment
ation fault.
[Switching to LWP 20365]
osmscout::RoutingService::ResolveRNodeCh
ainToList (this=this@entry=0xb140d4c8,
finalRouteNode=<optimized out>,
closedSet=
Python Exception <type 'exceptions.Index
Error'> list index out of range:
std::unordered_set with 6621 element
s = {...}, nodes=std::list)
at /home/src1/osmscout/libosmscout/l
ibosmscout/src/osmscout/RoutingService.c
pp:306
306     /home/src1/osmscout/libosmscout/
libosmscout/src/osmscout/RoutingService.
cpp: No such file or directory.

**Comment by rinigus** [comment]
As you could see from previous comment (I just formatted it a bit), the problem is still at 

```
while (current->previousNode!=0) {
```

**Comment by Framstag** [comment]
That is strange, my current code is:

```
    ClosedSet::const_iterator current=closedSet.find(VNode(finalRouteNode));

    assert(current!=closedSet.end());

    while (current->previousNode!=0) {
      ClosedSet::const_iterator prev=closedSet.find(VNode(current->previousNode));

      assert(prev!=closedSet.end());

      nodes.push_back(*current);

      current=prev;
    }

    nodes.push_back(*current);

    std::reverse(nodes.begin(),nodes.end());
```
There are two strategic assert that should make sure that this does not happen. Do you make a release build that drops the assertions? If not, are you sure, that the code is current and you did a clean recompile? Is it the same call to src/Routing as given at the top of the issue?

**Comment by rinigus** [comment]
I agree, it is very strange. I am now looking on what's going on by inserting printouts into the code. I am as puzzled as you are and I am now trying to establish that I do use the latest code. 

The code is compiled using default release: that's RelWithDebInfo if I understand correctly. I'll try plain Debug as well.

I did clean recompile (rm -rf build-rpm). 

The call is the same as the one in the top of the issue, but through the server. The same lib code was working fine on Desktop compile (other build dir). 

I hope its an error on my part and maybe there is something that lurks in. I'll look into it and will be back when I know more.

**Comment by rinigus** [comment]
It looks like assert is out from default build. So, when I used an older import on the desktop and after compilation in Debug mode, I do have a failed assert on L309: https://github.com/Framstag/libosmscout/blob/master/libosmscout/src/osmscout/RoutingService.cpp#L309

Let me recheck with a new import.

**Comment by rinigus** [comment]
And a new import works absolutely fine. So, the difference comes from imported maps. The old, failing import, was from 29 Oct - before you fixed the 'left turn and no access' bug. I guess this function should be somehow taking into account that the find maybe failing even with a good code, but bad maps

**Comment by rinigus** [comment]
Just to confirm - new import and new fixed lib work nicely on phone as well.
